Create saboya.md
Frogtek/developing-site pull request #14
Opened 2019-02-21 11:53 UTC by caudevilla

2019-02-21 12:01 UTC, durey requested changes

2019-02-21 12:01 UTC, durey commented on _authors/saboya.md
> +avatar: /assets/authors/saboya.jpg
¡Falta incluir la foto!

2019-02-21 12:12 UTC, durey approved these changes

2019-02-22 11:12 UTC, caudevilla commented on _authors/saboya.md
> +avatar: /assets/authors/saboya.jpg
La metí en otra pullrequest, pero ya veo que la has cerrado y has debido meter la foto por otro lado.

2019-02-22 11:12 UTC, merged

2019-02-22 16:37 UTC, durey commented
@caudevilla En esta PR tuya había metido la foto 😉