Add 2018-06-13-pamplona-software-crafters post
Frogtek/developing-site pull request #6
Opened 2018-06-13 21:32 UTC by francho

2018-06-13 22:36 UTC, durey requested changes
**Sobre el artículo**

Al empezar a leer pensé que habría algún comentario concreto sobre los contenidos de este año, no solo una descripción genérica del evento en sí. Sí, también está muy bien, pero quizá no enganche tanto...

**Sobre la ortografía**

Soy un :grinchus: de la escritura, jejeje, pero creo que es para mejor. Siempre da mejor imagen un medio escrito sin baches.

(En cualquier escrito hay comas y demás sujetas al criterio de cada uno, por supuesto, pero si pongo algo aquí es porque son correcciones impepinables, ¡no por fastidiar!) 🙏

2018-06-13 22:36 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Esta semana pasada he tenido la suerte de poder ir a uno de los más interesantes del panorama nacional: el [Pamplona Software Crafters](http://pamplonaswcraft.com/), y digo “la suerte” porque las ent
he tenido -> tuve ("este año he tenido" porque no ha acabado, pero "la semana pasada" ya acabó..., hace falta un pretérito indefinido)

2018-06-13 22:36 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Para mi el [#scpna](https://twitter.com/hashtag/scpna?src=hash) es especial por varias razones:
mí

2018-06-13 22:36 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Es un evento pequeño (120 asistentes de 80 empresas). No hay problemas de espacio, sabes que, si quieres ir a una charla no vas a tener que luchar con nadie para entrar.
sabes que, -> sin coma

o bien

sabes, si quieres ir a una charla, -> coma extra para diferenciar una aclaración

2018-06-13 22:36 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +En definitiva, es un evento creado por ([gracias cracks](http://540deg.com/#about)) y para desarrolladores, donde se cuida cada detalle. Tanto es así que, no conozco a nadie que haya ido y no quiera
gracias, cracks <- falta coma vocativa...

2018-06-13 22:36 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +En definitiva, es un evento creado por ([gracias cracks](http://540deg.com/#about)) y para desarrolladores, donde se cuida cada detalle. Tanto es así que, no conozco a nadie que haya ido y no quiera
Tanto es así que no -> coma incorrecta antes de verbo

2018-06-13 22:36 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +En definitiva, es un evento creado por ([gracias cracks](http://540deg.com/#about)) y para desarrolladores, donde se cuida cada detalle. Tanto es así que, no conozco a nadie que haya ido y no quiera
Yo por lo menos espero -> coma incorrecta antes de verbo

2018-06-13 22:36 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Mientras tendré que conformarme con ver el video resumen y tratar de asimilar todo lo que he aprendido y apuntado estos días.
Mientras, tendré -> adverbio al principio de oración va seguido de coma

2018-06-14 06:25 UTC, francho commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Para mi el [#scpna](https://twitter.com/hashtag/scpna?src=hash) es especial por varias razones:
Gracias @durey, la verdad es que lo escribí anoche del tirón y no me paré a revisar la ortografía.

Lo he escrito de forma generalista porque no conseguí hilar todos los apuntes que tomé y darles forma de un solo artículo. Así que prefiero contaros eso en la miniformación esta tarde y centrarme en detalles concretos que nos pueden ayudar.

Igual de alguna cosa concreta me sale un artículo

2018-06-14 09:35 UTC, candidogutierrez approved these changes

2018-06-14 10:03 UTC, figarocorso commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Esta semana pasada he tenido la suerte de poder ir a uno de los más interesantes del panorama nacional: el [Pamplona Software Crafters](http://pamplonaswcraft.com/), y digo “la suerte” porque las ent
@durey eso de `pretérito indefinido` ya no se lleva, ¿o sí? 

Hay que renovarse :-) http://www.rae.es/diccionario-panhispanico-de-dudas/apendices/modelos-de-conjugacion-verbal

> En lo que respecta a la terminología académica, debe tenerse en cuenta que el llamado pretérito indefinido en la Gramática de la lengua española de 1931 pasó a denominarse pretérito perfecto simple en el Esbozo de una nueva gramática de la lengua española (1973), y que esta última es la denominación utilizada en los cuadros de conjugación.

2018-06-14 10:10 UTC, durey commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Esta semana pasada he tenido la suerte de poder ir a uno de los más interesantes del panorama nacional: el [Pamplona Software Crafters](http://pamplonaswcraft.com/), y digo “la suerte” porque las ent
Tengo varios correctores profesionales en la familia, de la vieja escuela, y aprendí de ellos, así que me llevo perlas así a la tumba 😆. Ellos lo siguen usando para diferenciar dos posibles situaciones del pretérito perfecto simple, te sorprenderían los tecnicismos que usan al hablar de ortografía que no dice la gente ni salen en el diccionario...

2018-06-14 10:13 UTC, durey approved these changes

2018-06-14 15:29 UTC, merged

2018-06-14 16:43 UTC, figarocorso commented on _posts/2018-06-13-pamplona-software-crafters.md
> +Esta semana pasada he tenido la suerte de poder ir a uno de los más interesantes del panorama nacional: el [Pamplona Software Crafters](http://pamplonaswcraft.com/), y digo “la suerte” porque las ent
Ha sido una gozada leer tus comentarios, y el post ;-)